apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcitydata
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
