apiVersion: v1
kind: Service
metadata:
  name: teamcity
  namespace: default
  labels:
    name: teamcity
spec:
  selector:
    app: teamcity
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8111
